delete from events;
delete from locations;

insert into locations(id, city, country, number, post_code, state, street) values (1, 'Genf', 'Switzerland', 65, 1205, 'Genève', 'Boulevard Carl-Vogt');
insert into locations(id, city, country, number, post_code, state, street) values (2, 'Genève', 'Switzerland', 65, 1205, 'Genève', 'Boulevard Carl-Vogt');
insert into locations(id, city, country, number, post_code, state, street) values (3, 'Zurich', 'Switzerland', 65, 8005, 'Zurich',  'Pfingstweidstrasse');

insert into events(id, description, event_image, event_start_date, name, location_id) values (1, 'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l''imprimerie depuis les années 1500, quand un peintre anonyme assembla ensemble des morceaux de texte pour réaliser un livre spécimen de polices de texte', 'http://res.cloudinary.com/yhabib/image/upload/v1489410802/Events_App/AreYouColorBlind.jpg', {ts '2017-04-30 10:30:00.00'},'Are you color blind?', 1);
insert into events(id, description, event_image, event_start_date, name, location_id) values (2, 'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l''imprimerie depuis les années 1500, quand un peintre anonyme assembla ensemble des morceaux de texte pour réaliser un livre spécimen de polices de texte', 'http://res.cloudinary.com/yhabib/image/upload/v1489410802/Events_App/AuRythmeDeVosMurs.jpg', {ts '2017-08-10 10:30:00.00'}, 'Au Rythme de Vos Murs', 3);
insert into events(id, description, event_image, event_start_date, name, location_id) values (3, 'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l''imprimerie depuis les années 1500, quand un peintre anonyme assembla ensemble des morceaux de texte pour réaliser un livre spécimen de polices de texte', 'http://res.cloudinary.com/yhabib/image/upload/v1489410802/Events_App/CloseTheImmunization.jpg', {ts '2017-06-12 10:30:00.00'}, 'Close the Imunisation', 3);
insert into events(id, description, event_image, event_start_date, name, location_id) values (4, 'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l''imprimerie depuis les années 1500, quand un peintre anonyme assembla ensemble des morceaux de texte pour réaliser un livre spécimen de polices de texte', 'http://res.cloudinary.com/yhabib/image/upload/v1489410802/Events_App/ColereParoleAfficheAction.jpg', {ts '2017-12-12 10:30:00.00'}, 'Colere et parole', 2);
